
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_URL=https://kohei-naka.github.io/hachimura-stats/data/games.json
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/health'); sys.exit(0)"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      # IMPORTANT: browser accesses backend via localhost:8000
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
